Repository YouDontSayIt-dev/Battleships-Clone, pull requests merged in 2023-05, with the labels that each got.

#2 Implemented hunt and search behavior of AI
  coordinates.py
  game.py
Labels: bug, enhancement, help wanted

#7 updated main menu + turncounter + color of elements
  game.py
Labels: enhancement

#9 Optimized AI pattern
  game.py
Labels: enhancement

#10 Separated functions into different files
  __pycache__/aiAgent.cpython-311.pyc
  __pycache__/boardSettings.cpython-311.pyc
  __pycache__/gameLogic.cpython-311.pyc
  __pycache__/globalVariables.cpython-311.pyc
  __pycache__/shipPlacement.cpython-311.pyc
  aiAgent.py
  boardSettings.py
  game.py
  gameLogic.py
  globalVariables.py
  shipPlacement.py
  splashScreen.py
Labels: documentation

#11 Ai optimization v3
  __pycache__/aiAgent.cpython-310.pyc
  __pycache__/boardSettings.cpython-310.pyc
  __pycache__/gameLogic.cpython-310.pyc
  __pycache__/globalVariables.cpython-310.pyc
  __pycache__/globalVariables.cpython-311.pyc
  __pycache__/shipPlacement.cpython-310.pyc
  __pycache__/splashScreen.cpython-310.pyc
  __pycache__/splashScreen.cpython-311.pyc
  aiAgent.py
  globalVariables.py
Labels: enhancement

#15 Changes on the GUI of the game
  __pycache__/aiAgent.cpython-310.pyc
  __pycache__/aiAgent.cpython-311.pyc
  __pycache__/boardSettings.cpython-310.pyc
  __pycache__/boardSettings.cpython-311.pyc
  __pycache__/gameLogic.cpython-310.pyc
  __pycache__/gameLogic.cpython-311.pyc
  __pycache__/globalVariables.cpython-310.pyc
  __pycache__/globalVariables.cpython-311.pyc
  __pycache__/shipPlacement.cpython-310.pyc
  __pycache__/shipPlacement.cpython-311.pyc
  __pycache__/splashScreen.cpython-310.pyc
  __pycache__/splashScreen.cpython-311.pyc
  boardSettings.py
  game.py
  shipPlacement.py
  splashScreen.py
Labels: bug, enhancement

#23 Added fog of war for enemy ships
  __pycache__/boardSettings.cpython-310.pyc
  __pycache__/gameLogic.cpython-310.pyc
  __pycache__/globalVariables.cpython-310.pyc
  __pycache__/shipPlacement.cpython-310.pyc
  boardSettings.py
  gameLogic.py
  shipPlacement.py
Labels: enhancement
